djangotwitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import SearchView

from posts.views import TimeLineView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("profiles/", include("profiles.urls")),
    path("select2/", include("django_select2.urls")),
    path("", TimeLineView.as_view(), name="timeline"),  # Timeline is the home page of project
    path("search/", SearchView.as_view(), name="search"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (
    UserPostListView,
    CreatePostView,
    EditPostView,
    UserDetailPostView,
    OtherUserDetailPostView,
    TagPostsView,
    UnfollowTagView,
    FollowTagView,
    TagFollowListView,
    DeletePostView,
)

app_name = "posts"

urlpatterns = [
    path("my-posts/", UserPostListView.as_view(), name="user_posts"),
    path("create-post/", CreatePostView.as_view(), name="create_post"),
    path("edit-post/<int:pk>/", EditPostView.as_view(), name="edit_post"),
    path(
        "detail-post/<int:pk>/", UserDetailPostView.as_view(), name="user_detail_post"
    ),
    path(
        "post/<int:pk>/",
        OtherUserDetailPostView.as_view(),
        name="other_user_detail_post",
    ),
    path("tag-list/", TagFollowListView.as_view(), name="tag_list"),
    path("tag/<int:tag_id>/", TagPostsView.as_view(), name="tag_posts"),
    path("follow-tag/<int:tag_id>/", FollowTagView.as_view(), name="follow_tag"),
    path("unfollow-tag/<int:tag_id>/", UnfollowTagView.as_view(), name="unfollow_tag"),
    path("delete-post/<int:pk>/", DeletePostView.as_view(), name="delete_post"),
]

profiles/urls.py
from django.urls import path

from profiles.views import (
    UserProfileView,
    CustomLoginView,
    CustomLogoutView,
    ChangePasswordView,
    RegisterView,
    OtherProfileView,
    FollowView,
    UnfollowView,
    FollowPageView,
)

app_name = "profiles"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile/<int:id>/", OtherProfileView.as_view(), name="other_profile"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("follow/<int:user_id>/", FollowView.as_view(), name="follow"),
    path("unfollow/<int:user_id>/", UnfollowView.as_view(), name="unfollow"),
    path("follow-page/", FollowPageView.as_view(), name="follow_page"),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post_images/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField("Tag", related_name="posts", blank=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title}"


class Image(models.Model):
    post = models.ForeignKey(Post, related_name="images", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images/")

    def __str__(self):
        return f"Image for {self.post.title}"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    parent = models.ForeignKey(
        "self", null=True, blank=True, related_name="replies", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Like by {self.user} on {self.post}"


class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Dislike by {self.user} on {self.post}"


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"


class TagFollow(models.Model):
    user = models.ForeignKey(User, related_name="tag_follows", on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, related_name="followers", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} follows {self.tag}"

posts/forms.py
from django import forms
from django_select2.forms import ModelSelect2TagWidget

from posts.models import Post, Image, Tag, Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(
                attrs={"rows": 2, "placeholder": "Write a comment..."}
            ),
        }


class TagWidget(ModelSelect2TagWidget):
    search_fields = ["name__icontains"]

    def value_from_datadict(self, data, files, name):
        """
        Overrides the default method `value_from_datadict` to retrieve tag values
        from the form data.

        Retrieves the values from the form data, and converts them into a list of
        primary keys. If the value is a digit, it is assumed to be a primary key
        of an existing tag. If the value is not a digit, it is assumed to be a
        tag name. It then searches for an existing tag with the given name, and
        if none is found, it creates a new one. The primary key of the tag is
        appended to the list of primary keys.

        Returns:
            list: A list of primary keys of tags.
        """
        values = super().value_from_datadict(data, files, name)
        tags = []
        for value in values:
            if value.isdigit():
                tags.append(value)
            else:
                tag, created = Tag.objects.get_or_create(name=value)
                tags.append(tag.id)
        return tags


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ["image"]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "featured_image", "content", "tags", "archived"]
        widgets = {
            "tags": TagWidget(
                model=Tag,
                search_fields=["name__icontains"],
            )
        }


class LikeForm(forms.Form):
    post_id = forms.IntegerField(widget=forms.HiddenInput())


class DislikeForm(forms.Form):
    post_id = forms.IntegerField(widget=forms.HiddenInput())


class SearchForm(forms.Form):
    query = forms.CharField(
        label="Search",
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search...",
            }
        ),
    )

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DetailView,
    View,
    DeleteView,
)
from django.shortcuts import get_object_or_404
from django.db.models import Q

from posts.forms import PostForm, SearchForm, CommentForm
from posts.models import Post, Image, Like, Dislike, Tag, Comment, TagFollow
from profiles.models import Follow
from profiles.models import Profile


# Create your views here.


class SearchView(ListView):
    """
    View for search
    """

    template_name = "search_results.html"
    context_object_name = "search_results"

    def get_queryset(self):
        return Post.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = SearchForm(self.request.GET or None)
        query = ""
        profiles = []
        posts = []
        tags = []

        if form.is_valid():
            query = form.cleaned_data.get("query", "")
            if query:
                profiles = Profile.objects.filter(
                    user__username__icontains=query, archived=False
                )
                posts = Post.objects.filter(title__icontains=query, archived=False)
                tags = Tag.objects.filter(name__icontains=query)

        context.update(
            {
                "form": form,
                "query": query,
                "profiles": profiles,
                "posts": posts,
                "tags": tags,
            }
        )
        return context


class UserPostListView(LoginRequiredMixin, ListView):
    """
    View for user posts
    """

    model = Post
    template_name = "user_posts.html"
    context_object_name = "posts"
    login_url = "profiles:login"
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user).order_by("-created_at")


class CreatePostView(LoginRequiredMixin, CreateView):
    """
    View for creating post
    """

    model = Post
    template_name = "create_post.html"
    form_class = PostForm
    login_url = "profiles:login"
    success_url = reverse_lazy("posts:user_posts")

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        images = self.request.FILES.getlist("image")
        for image in images:
            Image.objects.create(image=image, post=self.object)
        messages.success(self.request, "your post has been created")
        return response


class EditPostView(LoginRequiredMixin, UpdateView):
    """
    View for editing post
    """

    model = Post
    template_name = "edit_post.html"
    form_class = PostForm
    login_url = "profiles:login"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

    def form_valid(self, form):
        response = super().form_valid(form)
        images = self.request.FILES.getlist("image")
        for image in images:
            Image.objects.create(image=image, post=self.object)
        messages.success(self.request, "your post has been updated")
        return response

    def get_success_url(self):
        return reverse("posts:user_detail_post", kwargs={"pk": self.object.pk})


class UserDetailPostView(LoginRequiredMixin, DetailView):
    """
    View for user's post
    """

    model = Post
    template_name = "user_detail_post.html"
    context_object_name = "post"
    login_url = "profiles:login"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        post = self.get_object()

        comments = Comment.objects.filter(post=post, parent=None).order_by(
            "-created_at"
        )
        context["comments"] = comments
        context["comment_form"] = CommentForm()

        context["user_liked"] = Like.objects.filter(user=user, post=post).exists()
        context["user_disliked"] = Dislike.objects.filter(user=user, post=post).exists()
        return context

    def post(self, request, *args, **kwargs):
        """
        Add like or dislike and comment to post
        """
        post = self.get_object()
        user = request.user

        if "like" in request.POST:
            like_exists = Like.objects.filter(user=user, post=post).exists()
            dislike_exists = Dislike.objects.filter(user=user, post=post).exists()

            if dislike_exists:
                Dislike.objects.filter(user=user, post=post).delete()

            if not like_exists:
                Like.objects.create(user=user, post=post)
                messages.success(request, "You liked this post.")
            else:
                Like.objects.filter(user=user, post=post).delete()
                messages.success(request, "You unliked this post.")

        elif "dislike" in request.POST:
            dislike_exists = Dislike.objects.filter(user=user, post=post).exists()
            like_exists = Like.objects.filter(user=user, post=post).exists()

            if like_exists:
                Like.objects.filter(user=user, post=post).delete()

            if not dislike_exists:
                Dislike.objects.create(user=user, post=post)
                messages.success(request, "You disliked this post.")
            else:
                Dislike.objects.filter(user=user, post=post).delete()
                messages.success(request, "You undisliked this post.")
        elif "comment" in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = user
                comment.post = post
                parent_id = request.POST.get("parent_id")
                if parent_id:
                    parent_comment = Comment.objects.get(id=parent_id)
                    comment.parent = parent_comment
                comment.save()
                messages.success(request, "Your comment was added successfully.")
            else:
                messages.error(request, "There was an error adding your comment.")
        return redirect("posts:user_detail_post", pk=post.pk)


class OtherUserDetailPostView(DetailView):
    """
    View for other user's post
    """

    model = Post
    template_name = "other_detail_post.html"
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs.get("pk")
        post = get_object_or_404(Post, pk=post_id)

        comments = Comment.objects.filter(post=post, parent=None).order_by(
            "-created_at"
        )
        context["comments"] = comments
        context["comment_form"] = CommentForm()

        if self.request.user.is_authenticated:
            user = self.request.user
            context["user_liked"] = Like.objects.filter(user=user, post=post).exists()
            context["user_disliked"] = Dislike.objects.filter(
                user=user, post=post
            ).exists()
        context["post"] = post
        return context

    def post(self, request, *args, **kwargs):
        """
        Add like or dislike and comment to post
        """
        post = self.get_object()
        user = request.user

        if "like" in request.POST:
            like_exists = Like.objects.filter(user=user, post=post).exists()
            dislike_exists = Dislike.objects.filter(user=user, post=post).exists()

            if dislike_exists:
                Dislike.objects.filter(user=user, post=post).delete()

            if not like_exists:
                Like.objects.create(user=user, post=post)
                messages.success(request, "You liked this post.")
            else:
                Like.objects.filter(user=user, post=post).delete()
                messages.success(request, "You unliked this post.")

        elif "dislike" in request.POST:
            dislike_exists = Dislike.objects.filter(user=user, post=post).exists()
            like_exists = Like.objects.filter(user=user, post=post).exists()

            if like_exists:
                Like.objects.filter(user=user, post=post).delete()

            if not dislike_exists:
                Dislike.objects.create(user=user, post=post)
                messages.success(request, "You disliked this post.")
            else:
                Dislike.objects.filter(user=user, post=post).delete()
                messages.success(request, "You undisliked this post.")

        elif "comment" in request.POST:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.author = user
                comment.post = post
                parent_id = request.POST.get("parent_id")
                if parent_id:
                    parent_comment = Comment.objects.get(id=parent_id)
                    comment.parent = parent_comment
                comment.save()
                messages.success(request, "Your comment was added successfully.")
            else:
                messages.error(request, "There was an error adding your comment.")

        return redirect("posts:other_user_detail_post", pk=post.pk)


class FollowTagView(LoginRequiredMixin, View):
    """
    View for following a tag.
    """

    def post(self, request, tag_id):
        tag = get_object_or_404(Tag, id=tag_id)

        if not TagFollow.objects.filter(user=request.user, tag=tag).exists():
            TagFollow.objects.create(user=request.user, tag=tag)

        return HttpResponseRedirect(
            reverse_lazy("posts:tag_posts", kwargs={"tag_id": tag_id})

posts/templates/other_detail_post.html
{% extends "_base.html" %}
{% load form_filters %}

{% block content %}
    <div class="flex flex-col md:flex-row dark:bg-gray-900 min-h-screen">
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto space-y-8">

            {% include 'component/messages.html' %}

            <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 w-full max-w-3xl">

                <h2 class="text-2xl font-bold text-primary-800">
                    <a href="{% url "profiles:other_profile" post.author.profile.id %}" class="text-primary-700">
                        Author: {{ post.author }}
                    </a></h2>

                <h3 class="mt-4 text-xl font-bold text-gray-600">Title: {{ post.title }}
                    {% if post.archived %}<span class="text-red-500">[Archived]</span>{% endif %}</h3>
                <p class="text-gray-700 dark:text-gray-300 mt-4">{{ post.content }}</p>

                {% if post.featured_image %}
                    <div class="mt-4">
                        <img class="rounded-lg w-full h-auto" src="{{ post.featured_image.url }}"
                             alt="Featured Image">
                    </div>
                {% endif %}

                {% if post.images.all %}
                    <div class="flex mt-4 space-x-4">
                        {% for image in post.images.all %}
                            <img class="rounded-lg w-32 h-32 object-cover" src="{{ image.image.url }}"
                                 alt="Image">
                        {% endfor %}
                    </div>
                {% endif %}
                {% if post.tags.exists %}
                    <div class="mt-4 flex justify-between items-center">
                        <div class="flex flex-wrap space-x-4 space-y-2 overflow-x-auto">
                            <span class="text-gray-700 dark:text-gray-400">Tags:</span>
                            {% for tag in post.tags.all|dictsort:"name" %}
                                <span class="text-primary-700 hover:bg-gray-200 p-1">
                                    <a href="{% url 'posts:tag_posts' tag.id %}">#{{ tag.name }}</a>
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <div class="mt-4 flex justify-between items-center">
                    <div class="flex space-x-4">
                        <span class="text-gray-700 dark:text-gray-400">{{ post.created_at|date:"F j, Y" }}</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.comment_set.count }} Comments</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.like_set.count }} Likes</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.dislike_set.count }} Dislikes</span>
                    </div>

                </div>
                <div class="mt-4 flex justify-between items-center">
                    <form method="post" action="{% url 'posts:other_user_detail_post' post.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{ post.id }}">
                        {% if request.user.is_authenticated %}
                            <button type="submit" name="like"
                                    class="btn btn-primary text-gray-700 border rounded-lg border-gray-700 p-0.5 {% if user_liked %}text-red-700{% endif %}">
                                Like
                            </button>
                            <button type="submit" name="dislike"
                                    class="btn btn-secondary text-gray-700 border rounded-lg border-gray-700 p-0.5 {% if user_disliked %}text-red-700 {% endif %}">
                                Dislike
                            </button>
                        {% else %}
                            <p>You need to be logged in to like or dislike.</p>
                        {% endif %}
                    </form>
                </div>
                <div class="mt-4 mb-4 flex justify-between items-center">
                    {% if request.user.is_authenticated %}
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ comment_form.content|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" }}
                            <button name="comment" class="btn btn-primary text-white p-2 m-4 rounded-lg bg-primary-700">
                                Add Comment
                            </button>
                        </form>
                    {% else %}
                        <p>You must be logged in to comment.</p>
                    {% endif %}
                </div>
                {% if comments %}
                    <h2 class="mb-4 text-2xl font-bold text-primary-800">Comments</h2>
                    <div class="comments">
                        {% for comment in comments %}
                            {% include 'component/comment.html' with comment=comment %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/post_detail.html
{% extends "_base.html" %}

{% block content %}
    <div class="flex flex-col md:flex-row dark:bg-gray-900 min-h-screen">
        {% include 'component/dashboard.html' %}
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto space-y-8">

            {% include 'component/messages.html' %}

            <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 w-full max-w-3xl">

                <h2 class="text-2xl font-bold text-primary-800">{{ post.title }}
                    {% if post.archived %}<span class="text-red-500">[Archived]</span>{% endif %}</h2>
                <p class="text-gray-700 dark:text-gray-300 mt-4">{{ post.content }}</p>

                {% if post.featured_image %}
                    <div class="mt-4">
                        <img class="rounded-lg w-full h-auto" src="{{ post.featured_image.url }}"
                             alt="Featured Image">
                    </div>
                {% endif %}

                {% if post.images.all %}
                    <div class="flex mt-4 space-x-4">
                        {% for image in post.images.all %}
                            <img class="rounded-lg w-32 h-32 object-cover" src="{{ image.image.url }}"
                                 alt="Image">
                        {% endfor %}
                    </div>
                {% endif %}
                {% if post.tags.exists %}
                    <div class="mt-4 flex justify-between items-center">
                        <div class="flex flex-wrap space-x-4 space-y-2 overflow-x-auto">
                            <span class="text-gray-700 dark:text-gray-400">Tags:</span>
                            {% for tag in post.tags.all|dictsort:"name" %}
                                <span class="text-gray-700 dark:text-gray-400">#{{ tag.name }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <div class="mt-4 flex justify-between items-center">
                    <div class="flex space-x-4">
                        <span class="text-gray-700 dark:text-gray-400">{{ post.created_at|date:"F j, Y" }}</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.comments.count }} Comments</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.like_set.count }} Likes</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.dislike_set.count }} Dislikes</span>
                    </div>
                    <a href="{% url 'posts:edit_post' post.id %}"
                       class="text-primary-600 dark:text-primary-400">Edit Post</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts.html
{% extends "_base.html" %}

{% block content %}
    {% if not posts %}
        <h1>No posts</h1>
    {% else %}
        <h1>posts</h1>
        {% for post in posts %}
            <h2>{{ post.title }}</h2>
        {% endfor %}
    {% endif %}
{% endblock content %}

posts/templates/user_detail_post.html
{% extends "_base.html" %}
{% load form_filters %}

{% block content %}
    <div class="flex flex-col md:flex-row dark:bg-gray-900 min-h-screen">
        {% include 'component/dashboard.html' %}
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto space-y-8">
            {% include 'component/messages.html' %}
            <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 w-full max-w-3xl">

                <h2 class="text-2xl font-bold text-primary-800">{{ post.title }}
                    {% if post.archived %}<span class="text-red-500">[Archived]</span>{% endif %}</h2>
                <p class="text-gray-700 dark:text-gray-300 mt-4">{{ post.content }}</p>

                {% if post.featured_image %}
                    <div class="mt-4">
                        <img class="rounded-lg w-full h-auto" src="{{ post.featured_image.url }}"
                             alt="Featured Image">
                    </div>
                {% endif %}

                {% if post.images.all %}
                    <div class="flex mt-4 space-x-4">
                        {% for image in post.images.all %}
                            <img class="rounded-lg w-32 h-32 object-cover" src="{{ image.image.url }}"
                                 alt="Image">
                        {% endfor %}
                    </div>
                {% endif %}
                {% if post.tags.exists %}
                    <div class="mt-4 flex justify-between items-center">
                        <div class="flex flex-wrap space-x-4 space-y-2 overflow-x-auto">
                            <span class="text-gray-700 dark:text-gray-400">Tags:</span>
                            {% for tag in post.tags.all|dictsort:"name" %}
                                <span class="text-primary-700 hover:bg-gray-200 p-1">
                                    <a href="{% url 'posts:tag_posts' tag.id %}">#{{ tag.name }}</a>
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                <div class="mt-4 flex justify-between items-center">
                    <div class="flex space-x-4">
                        <span class="text-gray-700 dark:text-gray-400">{{ post.created_at|date:"F j, Y" }}</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.comment_set.count }} Comments</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.like_set.count }} Likes</span>
                        <span class="text-gray-700 dark:text-gray-400">• {{ post.dislike_set.count }} Dislikes</span>
                    </div>
                    <a href="{% url 'posts:edit_post' post.id %}"
                       class="text-primary-600 dark:text-primary-400">Edit Post</a>
                </div>
                <div class="mt-4 flex justify-between items-center">
                    <form method="post" action="{% url 'posts:user_detail_post' post.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{ post.id }}">
                        {% if request.user.is_authenticated %}
                            <button type="submit" name="like"
                                    class="btn btn-primary text-gray-700 border rounded-lg border-gray-700 p-0.5 {% if user_liked %}text-red-700{% endif %}">
                                Like
                            </button>
                            <button type="submit" name="dislike"
                                    class="btn btn-secondary text-gray-700 border rounded-lg border-gray-700 p-0.5 {% if user_disliked %}text-red-700 {% endif %}">
                                Dislike
                            </button>
                        {% else %}
                            <p>You need to be logged in to like or dislike.</p>
                        {% endif %}
                    </form>

                </div>
                <div class="mt-4 mb-4 flex justify-between items-center">
                    {% if request.user.is_authenticated %}
                        <form method="post" action="">
                            {% csrf_token %}
                            {{ comment_form.content|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" }}
                            <button name="comment"
                                    class="btn btn-primary text-white p-2 m-4 rounded-lg bg-primary-700">Add Comment
                            </button>
                        </form>
                    {% else %}
                        <p>You must be logged in to comment.</p>
                    {% endif %}
                </div>
                {% if comments %}
                    <h2 class="mb-4 text-2xl font-bold text-primary-800">Comments</h2>
                    <div class="comments">
                        {% for comment in comments %}
                            {% include 'component/comment.html' with comment=comment %}
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}