djangotwitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import SearchView

from posts.views import TimeLineView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("profiles/", include("profiles.urls")),
    path("select2/", include("django_select2.urls")),
    path("", TimeLineView.as_view(), name="timeline"),  # Timeline is the home page of project
    path("search/", SearchView.as_view(), name="search"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (
    UserPostListView,
    CreatePostView,
    EditPostView,
    UserDetailPostView,
    OtherUserDetailPostView,
    TagPostsView,
    UnfollowTagView,
    FollowTagView,
    TagFollowListView,
    DeletePostView,
)

app_name = "posts"

urlpatterns = [
    path("my-posts/", UserPostListView.as_view(), name="user_posts"),
    path("create-post/", CreatePostView.as_view(), name="create_post"),
    path("edit-post/<int:pk>/", EditPostView.as_view(), name="edit_post"),
    path(
        "detail-post/<int:pk>/", UserDetailPostView.as_view(), name="user_detail_post"
    ),
    path(
        "post/<int:pk>/",
        OtherUserDetailPostView.as_view(),
        name="other_user_detail_post",
    ),
    path("tag-list/", TagFollowListView.as_view(), name="tag_list"),
    path("tag/<int:tag_id>/", TagPostsView.as_view(), name="tag_posts"),
    path("follow-tag/<int:tag_id>/", FollowTagView.as_view(), name="follow_tag"),
    path("unfollow-tag/<int:tag_id>/", UnfollowTagView.as_view(), name="unfollow_tag"),
    path("delete-post/<int:pk>/", DeletePostView.as_view(), name="delete_post"),
]

profiles/urls.py
from django.urls import path

from profiles.views import (
    UserProfileView,
    CustomLoginView,
    CustomLogoutView,
    ChangePasswordView,
    RegisterView,
    OtherProfileView,
    FollowView,
    UnfollowView,
    FollowPageView,
)

app_name = "profiles"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile/<int:id>/", OtherProfileView.as_view(), name="other_profile"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("follow/<int:user_id>/", FollowView.as_view(), name="follow"),
    path("unfollow/<int:user_id>/", UnfollowView.as_view(), name="unfollow"),
    path("follow-page/", FollowPageView.as_view(), name="follow_page"),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Profile(models.Model):
    """
    Profile model for storing user profile information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"


class Follow(models.Model):
    """
    Follow model for storing user follow information.
    """

    follower = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE
    )
    followed = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.follower} follows {self.followed}"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth.models import User

from profiles.models import Profile


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user = self.instance.user
        if user.first_name:
            self.fields["first_name"].initial = user.first_name
        if user.last_name:
            self.fields["last_name"].initial = user.last_name

    def save(self, commit=True):
        user = self.instance.user
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return super().save(commit)

    class Meta:
        model = Profile
        fields = ["avatar", "bio", "archived"]


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "username"
        self.fields["password1"].widget.attrs["placeholder"] = "••••••••"
        self.fields["password2"].widget.attrs["placeholder"] = "••••••••"


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ["username", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "username"
        self.fields["password"].widget.attrs["placeholder"] = "••••••••"


class ChangePasswordForm(PasswordChangeForm):

    class Meta:
        model = User
        fields = ["old_password", "new_password1", "new_password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget.attrs["placeholder"] = "••••••••"
        self.fields["new_password1"].widget.attrs["placeholder"] = "••••••••"
        self.fields["new_password2"].widget.attrs["placeholder"] = "••••••••"

profiles/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import UpdateView, CreateView
from django.core.paginator import Paginator

from profiles.forms import ProfileForm, RegisterForm, LoginForm, ChangePasswordForm
from profiles.models import Profile, Follow
from posts.models import Post
from django.contrib.auth.models import User


# Create your views here.
class OtherProfileView(TemplateView):
    """
    View for other user profile.
    """
    template_name = "other_profile.html"
    model = Profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_id = self.kwargs.get("id")
        profile = get_object_or_404(Profile, pk=profile_id)
        posts = Post.objects.filter(author=profile.user, archived=False).order_by(
            "-created_at", "-updated_at"
        )

        # Implement pagination
        paginator = Paginator(posts, 12)  # Show 4 posts per page
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context["profile"] = profile
        context["posts"] = page_obj
        if self.request.user.is_authenticated:
            context["is_following"] = Follow.objects.filter(
                follower=self.request.user, followed=profile.user
            ).exists()
        return context


class UserProfileView(LoginRequiredMixin, UpdateView):
    """
    View for user profile.
    """
    model = Profile
    template_name = "profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("profiles:user_profile")
    login_url = "profiles:login"

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.is_valid():
            form.save()
        messages.success(self.request, "Profile updated successfully")
        return super().form_valid(form)


class CustomLoginView(LoginView):
    """
    View for login.
    """
    template_name = "login.html"
    redirect_authenticated_user = True
    form_class = LoginForm

    def get_success_url(self):
        return self.request.GET.get("next", "/")


class CustomLogoutView(LoginRequiredMixin, LogoutView):
    """
    View for logout.
    """
    next_page = "profiles:user_profile"
    login_url = "profiles:login"


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    """
    View for changing password.
    """
    template_name = "change_password.html"
    login_url = "profiles:login"
    form_class = ChangePasswordForm
    success_url = reverse_lazy("profiles:change_password")

    def form_valid(self, form):
        messages.success(self.request, "Password changed successfully")
        return super().form_valid(form)


class RegisterView(CreateView):
    """
    View for registering new user.
    """
    template_name = "register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("timeline")

    def form_valid(self, form):
        form.save()
        username = self.request.POST["username"]
        password = self.request.POST["password1"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, "Registration successful")
        # Create Profile for user after registration
        Profile.objects.create(user=user)
        return HttpResponseRedirect(self.success_url)


class FollowView(LoginRequiredMixin, View):
    """
    View for following a user.
    """

    def post(self, request, user_id):
        user_to_follow = get_object_or_404(User, id=user_id)
        profile_to_follow = get_object_or_404(Profile, user=user_to_follow)

        if request.user == user_to_follow:
            return redirect(
                reverse_lazy(
                    "profiles:other_profile", kwargs={"id": profile_to_follow.id}
                )
            )

        # Check if the follow relationship already exists
        if not Follow.objects.filter(
            follower=request.user, followed=user_to_follow
        ).exists():
            Follow.objects.create(follower=request.user, followed=user_to_follow)

        return redirect(
            reverse_lazy("profiles:other_profile", kwargs={"id": profile_to_follow.id})
        )


class UnfollowView(LoginRequiredMixin, View):
    """
    View for unfollowing a user.
    """

    def post(self, request, user_id):
        user_to_unfollow = get_object_or_404(User, id=user_id)
        profile_to_unfollow = get_object_or_404(Profile, user=user_to_unfollow)

        if request.user == user_to_unfollow:
            return redirect(
                reverse_lazy(
                    "profiles:other_profile", kwargs={"id": profile_to_unfollow.id}
                )
            )

        # Find and delete the follow relationship
        follow = Follow.objects.filter(
            follower=request.user, followed=user_to_unfollow
        ).first()
        if follow:
            follow.delete()

        return redirect(
            reverse_lazy(
                "profiles:other_profile", kwargs={"id": profile_to_unfollow.id}
            )
        )


class FollowPageView(LoginRequiredMixin, ListView):
    """
    View for displaying a user's followers and following.
    """

    template_name = "follow_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        user = get_object_or_404(User, id=user_id)
        context["followers"] = Follow.objects.filter(
            followed=user, follower__profile__archived=False
        )
        context["following"] = Follow.objects.filter(
            follower=user, followed__profile__archived=False
        )
        return context

    def get_queryset(self):
        # This is needed to avoid errors, but we are actually not using the default queryset.
        return Follow.objects.none()

profiles/templates/change_password.html
{% extends "_base.html" %}
{% load form_filters %}

{% block content %}
    <div class="flex flex-col md:flex-row min-h-screen dark:bg-gray-900">
        {% include 'component/dashboard.html' %}
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto">
            {% include 'component/messages.html' %}
            <h1 class="text-3xl text-primary-600">Change password</h1>
            <form class="space-y-4 md:space-y-6 w-1/2" method="post">
                {% csrf_token %}
                <div class="text-red-600 text-sm">{{ form.non_field_errors }}</div>
                {% for field in form %}
                    <div>
                        <label for="{{ field.id_for_label }}"
                               class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                            {{ field.label }}
                        </label>
                        <label>
                            {{ field|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" }}
                            {% if field.errors %}
                                <div class="text-red-600 text-sm">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        </label>
                    </div>
                {% endfor %}

                <button type="submit"
                        class="w-full text-white bg-primary-700 hover:bg-primary-800 
                                focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium 
                                rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 
                                dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    Change Password
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

profiles/templates/follow_page.html
{% extends "_base.html" %}

{% block content %}
    <div class="flex flex-col md:flex-row dark:bg-gray-900 min-h-screen">
        {% include 'component/dashboard.html' %}
        <div class="flex flex-col items-center justify-center px-6 py-12 mx-auto">

            <h1 class="text-3xl font-bold mb-8 text-primary-600 dark:text-primary-400">
                {{ user.username }}'s Followers and Following
            </h1>

            <h2 class="text-2xl font-semibold mt-6 mb-4 text-primary-700 dark:text-primary-300">Followers</h2>
            <ul class="space-y-4 w-full md:w-3/4">
                {% for follower in followers %}
                    <li class="bg-white shadow-lg border-2 border-gray-200 rounded-lg p-6 dark:bg-gray-800 dark:text-white hover:shadow-xl transition-shadow duration-200 ease-in-out">
                        <a class="text-lg font-medium hover:text-primary-600 dark:hover:text-primary-400"
                           href="{% url 'profiles:other_profile' follower.follower.profile.id %}">
                            {{ follower.follower.username }}
                        </a>
                    </li>
                {% empty %}
                    <li class="text-gray-500 dark:text-gray-400 text-lg">No followers yet.</li>
                {% endfor %}
            </ul>

            <h2 class="text-2xl font-semibold mt-10 mb-4 text-primary-700 dark:text-primary-300">Following</h2>
            <ul class="space-y-4 w-full md:w-3/4">
                {% for following in following %}
                    <li class="bg-white shadow-lg border-2 border-gray-200 rounded-lg p-6 dark:bg-gray-800 dark:text-white hover:shadow-xl transition-shadow duration-200 ease-in-out">
                        <a class="text-lg font-medium hover:text-primary-600 dark:hover:text-primary-400"
                           href="{% url 'profiles:other_profile' following.followed.profile.id %}">
                            {{ following.followed.username }}
                        </a>
                    </li>
                {% empty %}
                    <li class="text-gray-500 dark:text-gray-400 text-lg">Not following anyone yet.</li>
                {% endfor %}
            </ul>

        </div>
    </div>
{% endblock %}

profiles/templates/login.html
{% extends "_base.html" %}
{% load form_filters %}
{% load static %}


{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <!-- Logo and branding -->
            <a href="{% url 'profiles:login' %}"
               class="flex items-center text-2xl font-semibold text-gray-900 dark:text-white">
                <img class="w-36 h-36" src="{% static 'images/logo.png' %}" alt="logo">
            </a>
            <p class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
                DjangoTwitter
            </p>
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <!-- Login form heading -->
                    <h1 class="text-xl font-bold leading-tight tracking-tight 
                    text-gray-900 md:text-2xl dark:text-white">
                        Login
                    </h1>
                    <!-- Login form -->
                    <form class="space-y-4 md:space-y-6" method="post">
                        {% csrf_token %}
                        <div class="text-red-600 text-sm">{{ form.non_field_errors }}</div>
                        {% for field in form %}
                            <div>
                                <label for="{{ field.id_for_label }}"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                    {{ field.label }}
                                </label>
                                <label>
                                    {{ field|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" }}
                                    {% if field.errors %}
                                        <div class="text-red-600 text-sm">
                                            {{ field.errors }}
                                        </div>
                                    {% endif %}
                                </label>
                            </div>
                        {% endfor %}

                        <button type="submit"
                                class="w-full text-white bg-primary-700 hover:bg-primary-800 
                                focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium 
                                rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 
                                dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                            Login
                        </button>
                    </form>
                    <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                        Don’t have an account yet? <a href="{% url "profiles:register" %}"
                                                      class="font-medium text-primary-600 hover:underline dark:text-primary-500">create
                        account</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

profiles/templates/other_profile.html
{% extends "_base.html" %}
{% load form_filters %}

{% block content %}
    <div class="flex flex-col md:flex-row min-h-screen">
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto max-w-4xl">
            {% include 'component/messages.html' %}

            <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-6 mb-8 w-full">
                <div class="flex flex-col items-center">
                    <!-- Avatar -->
                    {% if profile.avatar %}
                        <div class="mb-4">
                            <img class="rounded-full w-64 h-64 object-cover border-4 border-primary-700 shadow-lg"
                                 src="{{ profile.avatar.url }}" alt="avatar">
                        </div>
                    {% endif %}
                    <!-- Profile Info -->
                    <h1 class="text-3xl font-bold text-primary-800">{{ profile.user.get_full_name }}</h1>
                    <span class="mt-4 text-gray-700 text-3xl">Bio:</span>
                    <p class="mt-4 text-lg text-gray-700">{{ profile.bio }}</p>

                    <!-- Follow/Unfollow Button -->
                    {% if request.user.is_authenticated %}
                        {% if not request.user == profile.user %}
                            {% if is_following %}
                                <form action="{% url 'profiles:unfollow' profile.user.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="mt-4 px-4 py-2 bg-gray-700 text-white rounded-lg hover:bg-gray-900">
                                        Unfollow
                                    </button>
                                </form>
                            {% else %}
                                <form action="{% url 'profiles:follow' profile.user.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="mt-4 px-4 py-2 bg-primary-700 text-white rounded-lg hover:bg-primary-900">
                                        Follow
                                    </button>
                                </form>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <!-- Display posts in a grid layout -->
            {% if posts %}
                <div class="w-full mt-8">
                    <h2 class="text-2xl font-bold mb-4 text-primary-800">Posts</h2>
                    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                        {% for post in posts %}
                            <div class="bg-white dark:bg-gray-800 shadow-lg rounded-lg overflow-hidden">
                                {% if post.featured_image %}
                                    <img class="w-24 h-24 object-cover" src="{{ post.featured_image.url }}"
                                         alt="post image">
                                {% endif %}
                                <div class="p-4">
                                    <h3 class="text-lg font-semibold text-primary-800">{{ post.title }}</h3>
                                    <p class="text-gray-700 mt-2">{{ post.content|slice:":100" }}...</p>
                                    <a href="{% url 'posts:other_user_detail_post' post.id %}"
                                       class="text-primary-700 mt-4 inline-block">Read more</a>
                                </div>
                            </div>
                        {% empty %}
                            <p>No posts available.</p>
                        {% endfor %}
                    </div>
                    {% if posts %}
                        <!-- Pagination controls -->
                        <div class="flex justify-center mt-8">
                            <div class="pagination">
                <span class="step-links text-primary-600">
        {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}
                    <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                    </span>

                    {% if posts.has_next %}
                        <a href="?page={{ posts.next_page_number }}">next</a>
                        <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
                            </div>
                        </div>
                    {% endif %}

                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

profiles/templates/profile.html
{% extends "_base.html" %}
{% load form_filters %}

{% block content %}
    <div class="flex flex-col md:flex-row min-h-screen dark:bg-gray-900">
        {% include 'component/dashboard.html' %}
        <div class="flex flex-col items-center justify-center px-8 py-8 w-full mx-auto">
            {% include 'component/messages.html' %}
            <h1 class="text-3xl text-primary-800">Hello {{ user }}</h1>
            <div class="mt-4 text-primary-600 space-x-4">
                <a href="{% url 'profiles:follow_page' %}"
                   class="hover:text-primary-500 underline">
                    followers: {{ user.followers.count }}
                </a>
                <span>|</span>
                <a href="{% url 'profiles:follow_page' %}"
                   class="hover:text-primary-500 underline">
                    following: {{ user.following.count }}
                </a>
            </div>
            <form class="space-y-4 md:space-y-6 w-3/4" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    <label class="block text-primary-600">username: </label>
                    <div class="m-2 bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2 p-2.5 disabled">{{ user }}</div>
                </div>
                <div>
                    {% if user.profile.avatar %}
                        <div><img class="rounded-full w-64 h-64" src="{{ user.profile.avatar.url }}" alt="avatar"></div>
                    {% endif %}
                    <label class="block text-primary-600"
                           for="{{ form.avatar.id_for_label }}">{{ form.avatar.label }}</label>
                    <div class="m-2">{{ form.avatar }}</div>
                </div>
                <div>
                    <label class="block text-primary-600"
                           for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                    <div class="m-2">{{ form.first_name|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2 p-2.5" }}</div>
                </div>
                <div>
                    <label class="block text-primary-600"
                           for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                    <div class="m-2">{{ form.last_name|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-1/2 p-2.5" }}</div>
                </div>
                <div>
                    <label class="block text-primary-600"
                           for="{{ form.bio.id_for_label }}">{{ form.bio.label }}</label>
                    <div class="m-2">{{ form.bio|add_classes:"bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" }}</div>
                </div>

                <div>
                    <label class="block text-primary-600"
                           for="{{ form.archived.id_for_label }}">{{ form.archived.label }}</label>
                    <div class="m-2">{{ form.archived }}</div>
                </div>


                <button class="btn btn-primary text-white p-3 m-3 rounded-lg bg-primary-700" type="submit">Update
                </button>
            </form>
        </div>
    </div>
{% endblock content %}