djangotwitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import SearchView

from posts.views import TimeLineView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("profiles/", include("profiles.urls")),
    path("select2/", include("django_select2.urls")),
    path("", TimeLineView.as_view(), name="timeline"),  # Timeline is the home page of project
    path("search/", SearchView.as_view(), name="search"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (
    UserPostListView,
    CreatePostView,
    EditPostView,
    UserDetailPostView,
    OtherUserDetailPostView,
    TagPostsView,
    UnfollowTagView,
    FollowTagView,
    TagFollowListView,
    DeletePostView,
)

app_name = "posts"

urlpatterns = [
    path("my-posts/", UserPostListView.as_view(), name="user_posts"),
    path("create-post/", CreatePostView.as_view(), name="create_post"),
    path("edit-post/<int:pk>/", EditPostView.as_view(), name="edit_post"),
    path(
        "detail-post/<int:pk>/", UserDetailPostView.as_view(), name="user_detail_post"
    ),
    path(
        "post/<int:pk>/",
        OtherUserDetailPostView.as_view(),
        name="other_user_detail_post",
    ),
    path("tag-list/", TagFollowListView.as_view(), name="tag_list"),
    path("tag/<int:tag_id>/", TagPostsView.as_view(), name="tag_posts"),
    path("follow-tag/<int:tag_id>/", FollowTagView.as_view(), name="follow_tag"),
    path("unfollow-tag/<int:tag_id>/", UnfollowTagView.as_view(), name="unfollow_tag"),
    path("delete-post/<int:pk>/", DeletePostView.as_view(), name="delete_post"),
]

profiles/urls.py
from django.urls import path

from profiles.views import (
    UserProfileView,
    CustomLoginView,
    CustomLogoutView,
    ChangePasswordView,
    RegisterView,
    OtherProfileView,
    FollowView,
    UnfollowView,
    FollowPageView,
)

app_name = "profiles"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile/<int:id>/", OtherProfileView.as_view(), name="other_profile"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("follow/<int:user_id>/", FollowView.as_view(), name="follow"),
    path("unfollow/<int:user_id>/", UnfollowView.as_view(), name="unfollow"),
    path("follow-page/", FollowPageView.as_view(), name="follow_page"),
]

templates/_base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content=
            "width=device-width, initial-scale=1.0">
    <title>Django + Tailwind CSS</title>

    {% compress css %}
        <link rel="stylesheet" href="{% static 'src/flowbite.min.css' %}">
        <link rel="stylesheet"
              href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body>
{% include 'header.html' %}
<div class="container mx-auto mt-4">
    {% block content %}
        
    {% endblock content %}
</div>
<script src="{% static 'src/flowbite.min.js' %}"></script>

</body>

</html>

templates/header.html
{% load static %}
<!-- header.html -->
<header class="mt-3">
    <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
        <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl">
            <a href="/" class="flex items-center">
                <img src="{% static 'images/logo.png' %}" class="mr-3 h-10 sm:h-15" alt="DjangoTwitter"/>
                <span class="self-center text-primary-700 text-xl font-semibold whitespace-nowrap dark:text-white">
                    DjangoTwitter
                </span>
            </a>
            <div class="flex items-center lg:order-2">
                {% if request.user.is_authenticated %}
                    <form method="post" action="{% url 'profiles:logout' %}">
                        {% csrf_token %}
                        <button type="submit"
                                class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4
                                focus:ring-primary-300 font-medium rounded-lg text-sm px-4 lg:px-5
                                py-2 lg:py-2.5 mr-2 dark:bg-primary-600 dark:hover:bg-primary-700
                                focus:outline-none dark:focus:ring-primary-800">Logout
                        </button>
                    </form>
                {% else %}
                    <a href="{% url 'profiles:login' %}"
                       class="text-white bg-primary-700 hover:bg-primary-800
                       focus:ring-4 focus:ring-primary-300 font-medium rounded-lg
                       text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:bg-primary-600
                       dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800">Sign in</a>
                {% endif %}
                <button data-collapse-toggle="mobile-menu-2" type="button"
                        class="inline-flex items-center p-2 ml-1 text-sm text-gray-500
                        rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none
                        focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700
                        dark:focus:ring-gray-600"
                        aria-controls="mobile-menu-2" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1
                              0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                              clip-rule="evenodd"></path>
                    </svg>
                    <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0
                              111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10
                              11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                              clip-rule="evenodd"></path>
                    </svg>
                </button>
            </div>
            <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                <ul class="flex flex-col mt-4 font-medium text-lg lg:flex-row lg:space-x-8 lg:mt-0">
                    <li>
                        <a href="/"
                           class="block py-2 pr-4 pl-3 ml-8 justify-center text-primary rounded lg:p-0 dark:text-white
                           {% if request.resolver_match.url_name == 'timeline' %}text-white bg-primary-700 lg:bg-transparent lg:text-primary-700{% endif %}"
                           aria-current="page">TimeLine</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'profiles:user_profile' %}"
                               class="block py-2 pr-4 pl-3 ml-8 justify-center text-primary rounded lg:p-0 dark:text-white
                               {% if request.resolver_match.url_name == 'user_profile' %}text-white bg-primary-700 lg:bg-transparent lg:text-primary-700{% endif %}">Profile</a>
                        </li>
                    {% endif %}

                    {% if request.user.is_authenticated and request.user.is_superuser %}
                        <li>
                            <a href="{% url 'admin:index' %}"
                               class="block py-2 pr-4 pl-3 ml-8 justify-center text-primary rounded lg:p-0 dark:text-white">
                                Admin Panel</a>
                        </li>
                    {% endif %}
                    <li class="flex items-center">
                        <form method="get" action="{% url 'search' %}" class="block py-2 pr-4 pl-3 ml-8 justify-center text-primary rounded lg:p-0 dark:text-white">
                            <input type="text" name="query" placeholder="Search..."
                                   class="px-2 py-1 border rounded-lg border-primary-700 text-sm"
                                   value="{{ request.GET.query }}">
                            <button type="submit"
                                    class="ml-2 px-2 py-1 bg-primary-700 text-white rounded-lg hover:bg-primary-800 text-sm">
                                Search
                            </button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <hr class="mt-3 border-gray-200 sm:mx-auto dark:border-gray-700">
</header>