djangotwitter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts.views import SearchView

from posts.views import TimeLineView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("profiles/", include("profiles.urls")),
    path("select2/", include("django_select2.urls")),
    path("", TimeLineView.as_view(), name="timeline"),  # Timeline is the home page of project
    path("search/", SearchView.as_view(), name="search"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (
    UserPostListView,
    CreatePostView,
    EditPostView,
    UserDetailPostView,
    OtherUserDetailPostView,
    TagPostsView,
    UnfollowTagView,
    FollowTagView,
    TagFollowListView,
    DeletePostView,
)

app_name = "posts"

urlpatterns = [
    path("my-posts/", UserPostListView.as_view(), name="user_posts"),
    path("create-post/", CreatePostView.as_view(), name="create_post"),
    path("edit-post/<int:pk>/", EditPostView.as_view(), name="edit_post"),
    path(
        "detail-post/<int:pk>/", UserDetailPostView.as_view(), name="user_detail_post"
    ),
    path(
        "post/<int:pk>/",
        OtherUserDetailPostView.as_view(),
        name="other_user_detail_post",
    ),
    path("tag-list/", TagFollowListView.as_view(), name="tag_list"),
    path("tag/<int:tag_id>/", TagPostsView.as_view(), name="tag_posts"),
    path("follow-tag/<int:tag_id>/", FollowTagView.as_view(), name="follow_tag"),
    path("unfollow-tag/<int:tag_id>/", UnfollowTagView.as_view(), name="unfollow_tag"),
    path("delete-post/<int:pk>/", DeletePostView.as_view(), name="delete_post"),
]

profiles/urls.py
from django.urls import path

from profiles.views import (
    UserProfileView,
    CustomLoginView,
    CustomLogoutView,
    ChangePasswordView,
    RegisterView,
    OtherProfileView,
    FollowView,
    UnfollowView,
    FollowPageView,
)

app_name = "profiles"

urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="user_profile"),
    path("profile/<int:id>/", OtherProfileView.as_view(), name="other_profile"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("follow/<int:user_id>/", FollowView.as_view(), name="follow"),
    path("unfollow/<int:user_id>/", UnfollowView.as_view(), name="unfollow"),
    path("follow-page/", FollowPageView.as_view(), name="follow_page"),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Profile(models.Model):
    """
    Profile model for storing user profile information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username}"


class Follow(models.Model):
    """
    Follow model for storing user follow information.
    """

    follower = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE
    )
    followed = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.follower} follows {self.followed}"

profiles/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth.models import User

from profiles.models import Profile


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user = self.instance.user
        if user.first_name:
            self.fields["first_name"].initial = user.first_name
        if user.last_name:
            self.fields["last_name"].initial = user.last_name

    def save(self, commit=True):
        user = self.instance.user
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return super().save(commit)

    class Meta:
        model = Profile
        fields = ["avatar", "bio", "archived"]


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "username"
        self.fields["password1"].widget.attrs["placeholder"] = "••••••••"
        self.fields["password2"].widget.attrs["placeholder"] = "••••••••"


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ["username", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["placeholder"] = "username"
        self.fields["password"].widget.attrs["placeholder"] = "••••••••"


class ChangePasswordForm(PasswordChangeForm):

    class Meta:
        model = User
        fields = ["old_password", "new_password1", "new_password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget.attrs["placeholder"] = "••••••••"
        self.fields["new_password1"].widget.attrs["placeholder"] = "••••••••"
        self.fields["new_password2"].widget.attrs["placeholder"] = "••••••••"

profiles/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, View, ListView
from django.views.generic.edit import UpdateView, CreateView
from django.core.paginator import Paginator

from profiles.forms import ProfileForm, RegisterForm, LoginForm, ChangePasswordForm
from profiles.models import Profile, Follow
from posts.models import Post
from django.contrib.auth.models import User


# Create your views here.
class OtherProfileView(TemplateView):
    """
    View for other user profile.
    """
    template_name = "other_profile.html"
    model = Profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_id = self.kwargs.get("id")
        profile = get_object_or_404(Profile, pk=profile_id)
        posts = Post.objects.filter(author=profile.user, archived=False).order_by(
            "-created_at", "-updated_at"
        )

        # Implement pagination
        paginator = Paginator(posts, 12)  # Show 4 posts per page
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        context["profile"] = profile
        context["posts"] = page_obj
        if self.request.user.is_authenticated:
            context["is_following"] = Follow.objects.filter(
                follower=self.request.user, followed=profile.user
            ).exists()
        return context


class UserProfileView(LoginRequiredMixin, UpdateView):
    """
    View for user profile.
    """
    model = Profile
    template_name = "profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("profiles:user_profile")
    login_url = "profiles:login"

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        if form.is_valid():
            form.save()
        messages.success(self.request, "Profile updated successfully")
        return super().form_valid(form)


class CustomLoginView(LoginView):
    """
    View for login.
    """
    template_name = "login.html"
    redirect_authenticated_user = True
    form_class = LoginForm

    def get_success_url(self):
        return self.request.GET.get("next", "/")


class CustomLogoutView(LoginRequiredMixin, LogoutView):
    """
    View for logout.
    """
    next_page = "profiles:user_profile"
    login_url = "profiles:login"


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    """
    View for changing password.
    """
    template_name = "change_password.html"
    login_url = "profiles:login"
    form_class = ChangePasswordForm
    success_url = reverse_lazy("profiles:change_password")

    def form_valid(self, form):
        messages.success(self.request, "Password changed successfully")
        return super().form_valid(form)


class RegisterView(CreateView):
    """
    View for registering new user.
    """
    template_name = "register.html"
    form_class = RegisterForm
    success_url = reverse_lazy("timeline")

    def form_valid(self, form):
        form.save()
        username = self.request.POST["username"]
        password = self.request.POST["password1"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, "Registration successful")
        # Create Profile for user after registration
        Profile.objects.create(user=user)
        return HttpResponseRedirect(self.success_url)


class FollowView(LoginRequiredMixin, View):
    """
    View for following a user.
    """

    def post(self, request, user_id):
        user_to_follow = get_object_or_404(User, id=user_id)
        profile_to_follow = get_object_or_404(Profile, user=user_to_follow)

        if request.user == user_to_follow:
            return redirect(
                reverse_lazy(
                    "profiles:other_profile", kwargs={"id": profile_to_follow.id}
                )
            )

        # Check if the follow relationship already exists
        if not Follow.objects.filter(
            follower=request.user, followed=user_to_follow
        ).exists():
            Follow.objects.create(follower=request.user, followed=user_to_follow)

        return redirect(
            reverse_lazy("profiles:other_profile", kwargs={"id": profile_to_follow.id})
        )


class UnfollowView(LoginRequiredMixin, View):
    """
    View for unfollowing a user.
    """

    def post(self, request, user_id):
        user_to_unfollow = get_object_or_404(User, id=user_id)
        profile_to_unfollow = get_object_or_404(Profile, user=user_to_unfollow)

        if request.user == user_to_unfollow:
            return redirect(
                reverse_lazy(
                    "profiles:other_profile", kwargs={"id": profile_to_unfollow.id}
                )
            )

        # Find and delete the follow relationship
        follow = Follow.objects.filter(
            follower=request.user, followed=user_to_unfollow
        ).first()
        if follow:
            follow.delete()

        return redirect(
            reverse_lazy(
                "profiles:other_profile", kwargs={"id": profile_to_unfollow.id}
            )
        )


class FollowPageView(LoginRequiredMixin, ListView):
    """
    View for displaying a user's followers and following.
    """

    template_name = "follow_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.request.user.id
        user = get_object_or_404(User, id=user_id)
        context["followers"] = Follow.objects.filter(
            followed=user, follower__profile__archived=False
        )
        context["following"] = Follow.objects.filter(
            follower=user, followed__profile__archived=False
        )
        return context

    def get_queryset(self):
        # This is needed to avoid errors, but we are actually not using the default queryset.
        return Follow.objects.none()

profiles/templates/component/dashboard.html
{% load static %}

<aside id="default-sidebar" class="md:w-1/4 lw:w-1/5 border-r border-gray-200 transition-transform"
       aria-label="Sidebar">
    <div class="overflow-y-auto py-4 px-3 rounded">
        <ul class="space-y-6 m-8 font-medium ">
            <li>
                <a href="{% url 'profiles:user_profile' %}"
                   class="flex items-center p-1 text-gray-900 {% if request.resolver_match.url_name == 'user_profile' %}bg-gray-200{% endif %}
                   rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-6 h-6 text-primary-800 dark:text-white" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="ms-3">Profile <small>({{ user }})</small></span>
                </a>
            </li>
            <li>
                <a href="{% url 'posts:user_posts' %}"
                   class="flex items-center p-1 text-gray-900 {% if request.resolver_match.url_name == 'user_posts' %}bg-gray-200{% endif %}
                   rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-6 h-6 text-primary-800 dark:text-white" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="ms-3">My Posts</span>
                </a>
            </li>
            <li>
                <a href="{% url 'profiles:change_password' %}"
                   class="flex items-center p-1 text-gray-900 {% if request.resolver_match.url_name == 'change_password' %}bg-gray-200{% endif %}
                   rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-6 h-6 text-primary-800 dark:text-white" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="ms-3">Change Password</span>
                </a>
            </li>
            <li>
                <a href="{% url 'profiles:follow_page' %}"
                   class="flex items-center p-1 text-gray-900 {% if request.resolver_match.url_name == 'follow_page' %}bg-gray-200{% endif %}
                   rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-6 h-6 text-primary-800 dark:text-white" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="ms-3">Followers & Following</span>
                </a>
            </li>
            <li>
                <a href="{% url 'posts:tag_list' %}"
                   class="flex items-center p-1 text-gray-900 {% if request.resolver_match.url_name == 'tag_list' %}bg-gray-200{% endif %}
                   rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                    <svg class="w-6 h-6 text-primary-800 dark:text-white" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"/>
                    </svg>
                    <span class="ms-3">Tags Following</span>
                </a>
            </li>

        </ul>
    </div>
</aside>